sudo: false

language: php

services:
  - docker

php:
  - 7.2
  
before_script:
  - composer self-update
  
script:
  - cd microservices/application/user_management/
  - composer test
  
install: true
