sudo: false

language: php

services:
  - docker

php:
  - 7.2
  
before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i
  
script:
  - cd microservices/application/user_management/
  - composer test
  
install: true
