sudo: false

language: php

services:
  - docker

php:
  - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
  
script:
  - cd microservices/application/user_management/
  - phpunit tests/UserTestCase.php
  
install: true
